server.port=8084

spring.datasource.url=jdbc:postgresql://prod-db-host:5432/epam_prod
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.example=WARN
logging.level.org.hibernate.SQL=WARN