spring.application.name=RestEpam
spring.profiles.active=local
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=epam
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=RestEpam
info.app.version=1.0.0
info.app.description=Gym CRM REST API
logging.pattern.level=%5p [txId:%X{transactionId}]
logging.level.org.example=INFO
jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.validity=3600