management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=RestEpam
info.app.version=1.0.0
info.app.description=Gym CRM REST API