spring.application.name=RestEpam

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=epam
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=epam
