server.port=8082

spring.datasource.url=jdbc:postgresql://dev-db-host:5432/epam_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG