server.port=8083

spring.datasource.url=jdbc:postgresql://stg-db-host:5432/epam_stg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.example=INFO
logging.level.org.hibernate.SQL=WARN